### PR TITLE
Added Globus as an identity provider

### PR DESCRIPTION
**Pull request by NickolausDS**
* Globus Login work for any provider Globus Auth supports
* Added tests, coverage of new code is 100%
* Added Sphinx docs

### CODE REVIEW

**Comment by lnielsen** [comment]
Thanks a lot for the contribution. We'll have to keep the contribution on hold for a bit because we're changing the license of Invenio from GPL to MIT. Unfortunately, discussion with our lawyers is taking longer than expected, and thus we cannot integrate code from non-CERN contributors until this has finished. I'm sorry about this.

**Comment by NickolausDS** [comment]
Thanks for the update, I hope the license transition goes smoothly.

**Comment by slint** [comment]
@NickolausDS we can merge this, though could you tell us what legal entity is the copyright holder for this code, so we can include it in the headers? Also, please check if the case is that since this code might have been written as part of an employment contract which grants your employer the copyright to all source code you write (keep in mind that this could also apply for code written outside of working hours), the copyright holder might be your employer.

**Comment by lnielsen** [comment]
@rpwagner @NickolausDS - I've rebased the PR and updated the copyright headers. Last thing before I press the merge button, could you please confirm that you license your PR under MIT License (since the old headers said GPL - which was probably just due to copy/paste)?

**Comment by NickolausDS** [comment]
@lnielsen Yes, confirming here to license this pull request under MIT. Thanks for switching that.

**Comment by lnielsen** [comment]
Merged. Thanks a lot for the contribution, and apologies for taking so long to merge.

**Comment by NickolausDS** [comment]
No need for an apology, I know licensing can get complex and take time to sort out all the details. 

Thanks for picking this back up, your help was much appreciated!

**Pull request merged**
