### PR TITLE
contrib: adds CERN groups after user is logged in

### PR DESCRIPTION
**Pull request by ioannistsanaktsidis**
* Removes session after logout.

Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>

### CODE REVIEW

**Comment by jirikuncar** [comment]
I'm just curious if there is any reason why we can't store the groups in `token.remote_account.extra_data`? We should refresh them anytime we refresh the token.

**Comment by ioannistsanaktsidis** [comment]
LGTM!

**Comment by jirikuncar** [comment]
@ioannistsanaktsidis `s/adds/addition of/` + rebase :shipit:

**Comment by ioannistsanaktsidis** [comment]
@jirikuncar  uppated and rebased!

**Pull request merged**
